language: node_js
node_js:
  - "v11.0.0" 
branches:
  only:
    - master
install:
  - npm install
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  on: master
  app: digicard-node
script: npm test
after_success: npm run coverage